name: 'Github Action Slack Notifications via Curl'
description: >
  'Notify Slack when a GitHub Action succeeds, fails, or is cancelled.'
  'Lightweight: only requires curl.'
author: Endcrawl
branding:
  icon: bell
  color: black
inputs:
  slack_webhook:
    description: Webhook URL for the custom slack app you've added to your workspace.
    required: true
runs:
  using: 'composite'
  steps:
    - run: $GITHUB_ACTION_PATH/notify-slack
      shell: bash
      env:
        SLACK_WEBHOOK: ${{ inputs.slack_webhook }}
        STATUS: ${{ job.status }}
        PR_NUMBER: ${{ github.event.number }}
        COMMIT_SHA: ${{ github.event.after }}
