name: 'Github Action Slack Notifications via Curl'
description: 'Notify Slack when a GitHub Action succeeds, fails, or is cancelled. Lightweight: only requires curl.'
author: Endcrawl
runs:
  using: 'composite'
  steps:
    - run: ${{ github.action_path }}/notify-slack
      shell: bash
